Actions: Notify about missing GitHub token

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,11 +41,17 @@ jobs:
 
     steps:
       - name: Create dispatch event
+        env:
+          GITHUB_TOKEN: ${{ secrets.KCIDB_WORKFLOW_TRIGGER_TOKEN }}
         run: |
+          if test -z "$GITHUB_TOKEN"; then
+            echo "GitHub token is missing." >&2
+            false
+          fi
           curl --no-progress-meter \
                -X POST \
                -H "Accept: application/vnd.github+json" \
-               -H "Authorization: token ${{ secrets.KCIDB_WORKFLOW_TRIGGER_TOKEN }}" \
+               -H "Authorization: token $GITHUB_TOKEN" \
                https://api.github.com/repos/kernelci/kcidb/dispatches \
                -d '{"event_type":"test","client_payload":{"kcidb_io_ref":"'"$GITHUB_REF"'"}}' |
                { ! grep '.\+'; }
